doc: fix code-block syntax
A code-block needs to be followed by a black line.

ERROR: Error in "code-block" directive:
maximum 1 argument(s) allowed, 13 supplied.

Signed-off-by: fliiiix <hi@l33t.name>