Require latest version of requests-unixsocket
requests-unixsocket 0.1.5 incorporates a fix for
	ValueError: UnixAdapter does not support specifying proxies
raised when any proxy related environment variables are present.

Fixes #138